services:
  web:
    image: nginx
    volumes:
      - ./nginx/nginx.conf:/tmp/nginx.conf
    environment: 
      - QUART_SERVER_ADDR=backend:9091  
    command: /bin/bash -c "envsubst < /tmp/nginx.conf > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'" 
    ports:
      - 443:443
    depends_on:
      - backend

  backend:
    build:
      context: quart
      target: dev-envs
    stop_signal: SIGINT
    environment:
      - QUART_SERVER_PORT=9091
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      -  mongo  

  mongo:
    image: mongo
